python -u run.py \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2 \
  --model ETSformer \
  --data ETTm2 \
  --features S \
  --seq_len 96 \
  --pred_len $96 \
  --e_layers 2 \
  --d_layers 2 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --des 'Exp' \
  --K 2 \
  --learning_rate 1e-5 \
  --itr 1

python -u run.py \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2 \
  --model ETSformer \
  --data ETTm2 \
  --features S \
  --seq_len 96 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 2 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --des 'Exp' \
  --K 2 \
  --learning_rate 1e-3 \
  --itr 1

python -u run.py \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2 \
  --model ETSformer \
  --data ETTm2 \
  --features S \
  --seq_len 96 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 2 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --des 'Exp' \
  --K 1 \
  --learning_rate 1e-3 \
  --itr 1

python -u run.py \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2 \
  --model ETSformer \
  --data ETTm2 \
  --features S \
  --seq_len 720 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 2 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --des 'Exp' \
  --K 3 \
  --learning_rate 3e-4 \
  --itr 1