python -u run.py \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange \
  --model ETSformer \
  --data custom \
  --features M \
  --seq_len 336 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 2 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --K 0 \
  --learning_rate 3e-5 \
  --itr 1

python -u run.py \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange \
  --model ETSformer \
  --data custom \
  --features M \
  --seq_len 720 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 2 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --K 0 \
  --learning_rate 1e-4 \
  --itr 1

python -u run.py \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange \
  --model ETSformer \
  --data custom \
  --features M \
  --seq_len 336 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 2 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --K 0 \
  --learning_rate 3e-4 \
  --itr 1

python -u run.py \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange \
  --model ETSformer \
  --data custom \
  --features M \
  --seq_len 192 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 2 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --K 0 \
  --learning_rate 1e-3 \
  --itr 1
